language: node_js

node_js:
  - stable
  - 6.4.0

install:
  - npm install

script:
  - npm run cover

# send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
